# Site settings
title: Prog 5 blog
email: Tom.verbesselt@gmail.com
description: "korte stukjes geschreven door cursisten prog 5"
baseurl: "http://tverbesselt.github.io/prog5/"
url: "http://tverbesselt.github.io/prog5/"
twitter_username: tomverbesselt
github_username:  tverbesselt
facebook_username:  tom.verbesselt

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 15
exclude: ["node_modules"]
